config/routes.rb
Rails.application.routes.draw do

  get 'pics/destroy'
  resources :albums
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: "index#index"
  root to: "index#discover"
  resources :photos
  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "logout" => "devise/sessions#destroy"
  end
  get "userProfile" => "index#editUserProfile"
  get "feed" => "index#feed"
  get "profile/:id" => "index#profile", as: 'profile'
  #get 'info/:id', to: "feed#info", as: 'info'
  delete 'pic/:id' => 'pics#destroy', as: 'pic'

  # post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  # post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  post "follow", to: "index#follow"
  post "unfollow", to: "index#unfollow"
  # post "like/album/:id_album", to: "index#like", as: "like/album"
  # delete "like/album/:id_album", to: "index#unlike", as: "unlike/album"
  post "like/photo/:id_photo", to: "index#like_photo", as: "like/photo"
  post "like/album/:id_album", to: "index#like_album", as: "like/album"
end

app/models/album.rb
class Album < ApplicationRecord
  acts_as_votable
  belongs_to :user
  #has_many :likes, as: :imageable
  has_many :pics, as: :imageable, dependent: :destroy
  validates_presence_of :title
  default_scope -> { order(created_at: :desc) }

  #Title (required): maximum 140 characters long.
  validates :title, presence: true, length: { maximum: 140 }
  #Description (required): maximum 300 characters long.
  validates :description, presence: true, length: { maximum: 300 }
  #Sharing mode (required): public or private.
    # Từ form đã mặc định là true hoặc false
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = Album.all
  end

  def show
  end

  def new
    @album = Album.new
  end

  def edit
  end

  def create
  @album = Album.new(album_params)
  @album.user_id = current_user.id
    if @album.save

      if params[:images]
        params[:images].each { |image|
        @album.pics.create(image: image)
      }
      end
      flash[:notice] = "Successfully added new album!"
      redirect_to "/userProfile"
    else
      flash[:alert] = "Error adding new album!"
      render :new
    end
  end

  def update
    if @album.update(album_params)
      if params[:images]
        params[:images].each do |image|
          existing_image = @album.pics.find {|pic| pic.image_file_name ==image.original_filename}
          @album.pics.create(image: image) unless existing_image
        end
      end
      flash[:notice] = "Successfully updated the album!"
      redirect_to "/userProfile"
    else
      flash[:alert] = "Error updating the album!"
      render :edit
    end
  end

  def destroy
    if  @album.destroy
      flash[:notice] = "Successfully destroyed the album!"
      redirect_to "/userProfile"
    else
      flash[:alert] = "Error destroying the album!"
      render :edit
    end
  end
  private
    def set_album
      @album = Album.find(params[:id])
    end
    def album_params
      params.require(:album).permit(:title, :description, :sharing_mode)
    end
end

app/views/albums/_form.html.erb
<%= simple_form_for(album, html: {multipart: true}) do |f| %>
              <div class="row">
                  <div class="col-12 col-lg-6">
                    <div class="form-group">
                      <label>Title</label>
                      <!-- <input type="text" class="form-control" placeholder="Photo Title"> -->
                      <%= f.text_field :title, class: "form-control", placeholder: "Photo Title" %>
                    </div>

                    <div class="form-group w-50">
                      <label>Sharing Mode</label>
                      <!-- <select class="form-control">
                        <option selected>Public</option>
                        <option>Private</option>
                      </select> -->
                      <%= f.select :sharing_mode, options_for_select([['Public', true], ['Private', false]]), class: 'form-control' %>
                    </div>

                  </div>

                  <div class=" col-12 col-lg-6">
                    <div class="form-group">
                      <label>Description</label>
                       <!-- <textarea class="form-control"rows="6" placeholder="Album Description"></textarea> -->
                      <%= f.text_area(:description,class: "form-control",rows: "6", placeholder: "Album Description") %>
                    </div>
                  </div>



              </div>

              <div class="row">
                <div class="col images">



                  <% if @album.pics.any? %>
                    <div id="images">
                      <% @album.pics.each do |pic| %>
                        <div id="pic-<%= pic.id %>" class="image">
                           <%= link_to pic, method: :delete,

                                            class: "delete-image",
                                            remote: true,
                                            title: "Delete Image" do %>
                              <img class="close m-1" src="/assets/cl.png" style="width:30px; height: 30px" />
                            <% end %>
                          <%= image_tag pic.image.url(:medium), style: "height: 180px;width:180px" %>
                        </div>
                      <% end %>
                    </div>
                  <% end %>
                   <div id="image-preview"></div>
                  <div class="upload-btn-wrapper mt-2 float-left">
                   <button class="btn"><img src="/assets/plus.png">
                    <%= f.input " " do %>
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    <% end %>
                    </button>
                  </div>
                </div>
              </div>

              <div class="row mt-5 m-1">
                <%= f.submit 'Saving', class: 'btn mr-2', type: "submit", value:"Save"%>
              <%if @album.pics.any? %>
                <%= link_to "Delete", album_path(@album), class: "a btn ml-2",
                                            type: "button",
                                           method: :delete,
                                         data: { confirm: 'Are you sure ?' } %>

              <% end %>

              </div>

            </div>
<% end %>

app/views/albums/edit.html.erb
<style type="text/css">
  .card{
    border: 4px solid white;
    border-top-left-radius: 9px;
    border-bottom-left-radius: 9px;
    background-color:#efe9e9;
    margin-bottom: 2px;z`
    transition: transform .2s;
    box-shadow: 5px 10px 8px #888888;
    /*box-shadow: 0 4px 0px 0 rgba(0, 0, 0, 0.1); */
  }
  img{
    border-radius: 9px;
  }

  .btn-secondary{
    border :1px solid #3c5899 ;
    color:#3c5899;
  }

  .btn-secondary:hover{
    background-color:  #3c5899 ;
    color: white;
  }

  .btn-secondary:active {
    background-color:  white;
    color:#3c5899;
  }

  .card:hover {
    transform: scale(0.95);
  }

  body{
    background-color: #d6bfbf24
  }

  .menu {
    color: #9e9191;
    transition: transform .2s;
  }

  .menu:hover {
    color: #3c5899;
    transform: scale(1.2);
  }

  .menu:active {
    color: #9e9191;
    transform: scale(1.05);
  }

  .page-link:hover{
    background-color:  #3c5899 ;
    color: white;
  }

  .page-link:active{
    background-color: white ;
    color:#3c5899;
  }

  .position-absolute{
    bottom:10px;

  }

  img.like{
    transition: transform .2s;

  }
  img.like:hover{
    transform: scale(1.1);
  }

  img.like:active{
    transform: scale(0.5);
  }

  .tabcontent {
    display: none;
  }

  .fancy {
    line-height: 1;
    text-align: center;
  }

  .fancy span {
    display: inline-block;
    position: relative;
  }

  .fancy span:before,.fancy span:after {
    position: absolute;
    height: 5px;
    border-bottom: 1px solid white;
    border-top: 1px solid white;
    top: 0;
    width: 600px;
  }

  .fancy span:before {
    right: 100%;
    margin-right: 15px;
  }

  .fancy span:after {
    left: 100%;
    margin-left: 15px;
  }

  img.album{
    position:absolute;
    border :1px solid white;
    height:200px;
    width:200px;
    bottom: 40px;
    top:40px;
    margin-left:20px;
  }

  img.photo{
    border :2px solid white;
    height: 276px;
    width: 250px;
    margin-left:0;

  }

  img.modalAlbum{
    width: 100%;
    height:500px;
    border-radius:10px;
  }

  img.modalPhoto{
    width: 100%;
    height:500px;
    border-radius:10px;
  }

  .upload-btn-wrapper {
    position: relative;
    overflow: hidden;
    display: inline-block;
    width : 180px;
    height: 180px;
  }

  button.btn {
    width:100%;
    height: 100%;
    border: 3px dashed #a78f8f;
    color: gray;
    background-color: #d6bfbf24;
    padding: 8px 20px;
    border-radius: 8px;
    font-size: 20px;
    font-weight: bold;
  }

  .upload-btn-wrapper input[type=file] {
    font-size: 600px;
    position: absolute;
    left: 0;
    top: 0;
    opacity: 0;
  }

  input.btn {
    background-color: green;
    color: white;
    transition: transform .2s;
  }

  input.btn:hover{
    background-color: #0080008f;
    transform: scale(1.1);
  }

  input.btn:active{
    background-color: #0080008f;
    transform: scale(1.05);
  }

  input.btn[type=button]{
    background-color: red;
    color: white;
    transition: transform .2s;
  }

  input.btn[type=button]:hover{
    background-color: #ff0000a8;
    color: white;
    transform: scale(1.1);
  }

  input.btn[type=button]:active{
    background-color: #ff0000a8;
    color: white;
    transform: scale(1.05);
  }
  .upload-btn-wrapper:hover{
    transition: transform .2s;
    transform: scale(0.95);
  }
  .img_wrp {
    display: inline-block;
    position: relative;
  }
  .close {
    position: absolute;
    top: 0;
    right: 0;
  }
  .image{
    display: inline-block;
    position: relative;
  }

  .delete-image{
    position: absolute;
    top: 5px;
    right: 5px;
    color: red;
  }

  a.a{
    background-color: red;
    color: white;
    transition: transform .2s;
  }

  a.a:hover{
    background-color: #ff0000a8;
    color: white;
    transform: scale(1.1);
  }

  a.a:active{
    background-color: #ff0000a8;
    color: white;
    transform: scale(1.05);
  }

  @media only screen and (max-width: 990px) {
    img.album{
      position:absolute;
      border :1px solid white;
      height: 180px;
      width:180px;
      margin-left:25px;
      bottom: 60px;
      top:35px;
    }
  }


</style>
<script type="text/javascript">
  $(document).ready(function(){
    choose();
  });
</script>
<!-- HEADER -->
<header>
  <div class="container">
    <div class="row">
      <div class="col-sm-5 col-md-7">
        <div class="container">
          <div class="row">
            <div class="col-sm-3 col-lg-3">
              <a class="navbar-brand text-white   mr-2 header float-right" style="height:45px;" href="<%= root_path %>"><b>Fotobook</b></a>
            </div>

            <div class="col-sm-9 col-lg-9">
              <input class="form-control mt-1 h-75" type="search" placeholder="Search Photo/Album" aria-label="Search">
            </div>

          </div>
        </div>
      </div>

      <div class="col-sm-5 col-md-5">
        <ul class="nav nav-pills float-right">


          <%  if !current_user.nil? %>

          <li class="nav-item">
            <div class="d-flex  align-items-center header" style="height:45px;">

              <img src="<%=current_user.avatar.url(:thumb) %>" class="rounded-circle mr-1" style=" width: 37px; height: 37px">
              <a class="nav-link text-white p-1 mr-md-3 "style="font-size: 14px" href="/userProfile"><b> <%=current_user.first_name.to_s%></b></a>
            </div>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white header pt-2" style="height:45px;   font-size: 17px" data-method="DELETE" href="<%= destroy_user_session_path %>"><b>Log out</b> </a>
          </li>
          <%   else  %>
          <li class="nav-item">
            <div class="d-flex  align-items-center header" style="height:45px;">
            </div>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white header pt-2" style="height:45px;   font-size: 17px" href="/signin"><b>Log In</b></a>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white header pt-2" datastyle="height:45px;   font-size: 17px" data-method="GET" href="<%= new_user_registration_path %>"><b>Sign Up</b></a>
          </li>
          <% end %>


        </ul>
      </div>
    </div>
  </div>
</header>


<br class="m-2">

<!-- MAIN -->
<main>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-lg-2">
        <ul class="nav flex-column ml-sm-5">
          <li class="nav-item">
            <a class="nav-link menu"  href="<%= root_path %>"><b>Feeds</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link menu" href="/discover"><b>Discover</b></a>
          </li>

        </ul>
      </div>

      <div class="col-sm-8 col-lg-9" style="background-color: white">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <h5 class="pt-4">New Album</h5>
              <hr>
            </div>
          </div>

          <%= render 'form', album: @album %>


        </div>
      </div>
    </div>
  </div>
</main>

app/views/albums/index.html.erb
<div class="container">
  <div class="row">
    <% @albums.each do |album| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <% if album.pics.any? %>
            <%= link_to image_tag(album.pics.first.image.url(:medium)), album %>
          <% end %>
          <div class="caption">
            <h3 class="text-center"><%= album.title %></h3>
            <p><%= album.description %></p>
            <p>
              <%= link_to "Edit", edit_album_path(album), class: "btn btn-warning" %>
              <%= link_to "Delete", album, class: "btn btn-danger pull-right",
                                           method: :delete,
                                           data: { confirm: 'Are you sure?' } %>
             </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/albums/new.html.erb
<style type="text/css">
  .card{
    border: 4px solid white;
    border-top-left-radius: 9px;
    border-bottom-left-radius: 9px;
    background-color:#efe9e9;
    margin-bottom: 2px;z`
    transition: transform .2s;
    box-shadow: 5px 10px 8px #888888;
    /*box-shadow: 0 4px 0px 0 rgba(0, 0, 0, 0.1); */
  }
  img{
    border-radius: 9px;
  }

  .btn-secondary{
    border :1px solid #3c5899 ;
    color:#3c5899;
  }

  .btn-secondary:hover{
    background-color:  #3c5899 ;
    color: white;
  }

  .btn-secondary:active {
    background-color:  white;
    color:#3c5899;
  }

  .card:hover {
    transform: scale(0.95);
  }

  body{
    background-color: #d6bfbf24
  }

  .menu {
    color: #9e9191;
    transition: transform .2s;
  }

  .menu:hover {
    color: #3c5899;
    transform: scale(1.2);
  }

  .menu:active {
    color: #9e9191;
    transform: scale(1.05);
  }

  .page-link:hover{
    background-color:  #3c5899 ;
    color: white;
  }

  .page-link:active{
    background-color: white ;
    color:#3c5899;
  }

  .position-absolute{
    bottom:10px;

  }

  img.like{
    transition: transform .2s;

  }
  img.like:hover{
    transform: scale(1.1);
  }

  img.like:active{
    transform: scale(0.5);
  }

  .tabcontent {
    display: none;
  }

  .fancy {
    line-height: 1;
    text-align: center;
  }

  .fancy span {
    display: inline-block;
    position: relative;
  }

  .fancy span:before,.fancy span:after {
    position: absolute;
    height: 5px;
    border-bottom: 1px solid white;
    border-top: 1px solid white;
    top: 0;
    width: 600px;
  }

  .fancy span:before {
    right: 100%;
    margin-right: 15px;
  }

  .fancy span:after {
    left: 100%;
    margin-left: 15px;
  }

  img.album{
    position:absolute;
    border :1px solid white;
    height:200px;
    width:200px;
    bottom: 40px;
    top:40px;
    margin-left:20px;
  }

  img.photo{
    border :2px solid white;
    height: 276px;
    width: 250px;
    margin-left:0;

  }

  img.modalAlbum{
    width: 100%;
    height:500px;
    border-radius:10px;
  }

  img.modalPhoto{
    width: 100%;
    height:500px;
    border-radius:10px;
  }

  .upload-btn-wrapper {
    position: relative;
    overflow: hidden;
    display: inline-block;
    width : 180px;
    height: 180px;
  }

  button.btn {
    width:100%;
    height: 100%;
    border: 3px dashed #a78f8f;
    color: gray;
    background-color: #d6bfbf24;
    padding: 8px 20px;
    border-radius: 8px;
    font-size: 20px;
    font-weight: bold;
  }

  .upload-btn-wrapper input[type=file] {
    font-size: 600px;
    position: absolute;
    left: 0;
    top: 0;
    opacity: 0;
  }

  input.btn {
    background-color: green;
    color: white;
    transition: transform .2s;
  }

  input.btn:hover{
    background-color: #0080008f;
    transform: scale(1.1);
  }

  input.btn:active{
    background-color: #0080008f;
    transform: scale(1.05);
  }

  input.btn[type=button]{
    background-color: red;
    color: white;
    transition: transform .2s;
  }

  input.btn[type=button]:hover{
    background-color: #ff0000a8;
    color: white;
    transform: scale(1.1);
  }

  input.btn[type=button]:active{
    background-color: #ff0000a8;
    color: white;
    transform: scale(1.05);
  }
  .upload-btn-wrapper:hover{
    transition: transform .2s;
    transform: scale(0.95);
  }
  .img_wrp {
    display: inline-block;
    position: relative;
  }
  .close {
    position: absolute;
    top: 0;
    right: 0;
  }
  .image{
    display: inline-block;
    position: relative;
  }

  .delete-image{
    position: absolute;
    top: 5px;
    right: 5px;
    color: red;
  }

  @media only screen and (max-width: 990px) {
    img.album{
      position:absolute;
      border :1px solid white;
      height: 180px;
      width:180px;
      margin-left:25px;
      bottom: 60px;
      top:35px;
    }
  }


</style>
<script type="text/javascript" scr='/assets/index.js'></script>
<script type="text/javascript">

  $(document).ready(function(){
    choose();
  }
  );

</script>

<!-- HEADER -->
<header>
  <div class="container">
    <div class="row">
      <div class="col-sm-5 col-md-7">
        <div class="container">
          <div class="row">
            <div class="col-sm-3 col-lg-3">
              <a class="navbar-brand text-white   mr-2 header float-right" style="height:45px;" href="<%= root_path %>"><b>Fotobook</b></a>
            </div>

            <div class="col-sm-9 col-lg-9">
              <input class="form-control mt-1 h-75" type="search" placeholder="Search Photo/Album" aria-label="Search">
            </div>

          </div>
        </div>
      </div>

      <div class="col-sm-5 col-md-5">
        <ul class="nav nav-pills float-right">


          <%  if !current_user.nil? %>

          <li class="nav-item">
            <div class="d-flex  align-items-center header" style="height:45px;">

              <img src="<%=current_user.avatar.url(:thumb) %>" class="rounded-circle mr-1" style=" width: 37px; height: 37px">
              <a class="nav-link text-white p-1 mr-md-3 "style="font-size: 14px" href="/userProfile"><b> <%=current_user.first_name.to_s%></b></a>
            </div>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white header pt-2" style="height:45px;   font-size: 17px" data-method="DELETE" href="<%= destroy_user_session_path %>"><b>Log out</b> </a>
          </li>
          <%   else  %>
          <li class="nav-item">
            <div class="d-flex  align-items-center header" style="height:45px;">
            </div>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white header pt-2" style="height:45px;   font-size: 17px" href="/signin"><b>Log In</b></a>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white header pt-2" datastyle="height:45px;   font-size: 17px" data-method="GET" href="<%= new_user_registration_path %>"><b>Sign Up</b></a>
          </li>
          <% end %>


        </ul>
      </div>
    </div>
  </div>
</header>


<br class="m-2">

<!-- MAIN -->
<main>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-lg-2">
        <ul class="nav flex-column ml-sm-5">
          <li class="nav-item">
            <a class="nav-link menu"  href="<%= root_path %>"><b>Feeds</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link menu" href="/discover"><b>Discover</b></a>
          </li>

        </ul>
      </div>

      <div class="col-sm-8 col-lg-9" style="background-color: white">
        <div class="container">
          <div class="row">
            <div class="col-12">
              <h5 class="pt-4">New Album</h5>
              <hr>
            </div>
          </div>
          <%= render 'form', album: @album %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @album.description %>
</p>

<p>
  <strong>Sharing mode:</strong>
  <%= @album.sharing_mode %>
</p>

<div>
  <% @album.pics.each do |pic| %>
        <%= link_to image_tag(pic.image.url(:medium)), pic.image.url, data: { gallery: ''} %>
        <% end %>
</div>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>